apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: base-container
      labels:
        io.openshift.tags: rhel8
    spec:
      source:
        git:
          ref: main
          uri: "https://github.com/txsvc/ccollections.git"
        #contextDir: base-container
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: base-container/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: base-container:1.0-1
          namespace: openshift
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
